#!/usr/bin/env ruby
require 'rubygems'
require 'fileutils'
require 'yaml'
require 'open3'
require 'erb'
require 'maruku'
require 'hpricot'



$here = File.expand_path(File.dirname(__FILE__))
$config = YAML.load_file("#$here/config.yaml")
#$root = File.join($here, '..')
$base = "#$here/#{$config['lang']}"
$tpl = File.join($here, 'tpl')


def book2html(&block)

	block.call
	
end

def usage
	puts <<USAGE
Usage:
	book2html: [OPTION...]

Options:
	no options yet! :-)
USAGE
end

def copy_template_files
	FileUtils.mkdir_p($base)
	FileUtils.mkdir_p(File.join($base,"css"))
	FileUtils.mkdir_p(File.join($base,"img"))
	FileUtils.cp_r("#$here/tpl/css/.", File.join($base,"css"))
	FileUtils.cp_r("#$here/tpl/img/.", File.join($base,"img"))
end



book2html do 
	abort = false
	copy_template_files
	template = ERB.new(File.read("#$tpl/template.erb"))

	print "\t\tConvert book to html... "

	$config['order'].each do |cap|
		File.open(File.join($base, "#{cap}.html"), 'w') do |file|
			h1 = cap["title"]
			puts h1
       		file.write(template.result(binding))
    	end	
	end

	['index', 'about', 'colateral'].each do |file|
		File.open(File.join($base, "#{file}.html"), 'w') do |file|
       		file.write(template.result(binding))
    	end
	end
	
	unless abort
		puts "done"
	end
end


