#!/usr/bin/env ruby
require 'rubygems'
require 'fileutils'
require 'yaml'
require 'open3'
require 'erb'
require 'maruku'
require 'hpricot'



$here = File.expand_path(File.dirname(__FILE__))
$config = YAML.load_file("#$here/config.yaml")
#$root = File.join($here, '..')
$base = "#$here/#{$config['lang']}"
$tpl = File.join($here, 'tpl')


def book2html(&block)

	block.call
	
end

def usage
	puts <<USAGE
Usage:
	book2html: [OPTION...]

Options:
	no options yet! :-)
USAGE
end

def copy_template_files
	FileUtils.mkdir_p($base)
	FileUtils.mkdir_p(File.join($base,"css"))
	FileUtils.mkdir_p(File.join($base,"img"))
	FileUtils.cp_r("#$here/tpl/css/.", File.join($base,"css"))
	FileUtils.cp_r("#$here/tpl/img/.", File.join($base,"img"))
end



book2html do 
	abort = false
	copy_template_files
	template = ERB.new(File.read("#$tpl/template.erb"))

	print "\tConvert book to html... "

  i = 0 
  t = Time.now
  toc = []
	$config['order'].each do |item|
		File.open(File.join($base, "cap#{i}.html"), 'w') do |file|
			toc << h1 = item["cap#{i}"]["title"]
			body = Maruku.new(File.read(File.join($here, "cap" + i.to_s + '.markdown'))).to_html
			body = Hpricot(body)
			body.search("h1").remove
      file.write(template.result(binding))
    	end	
    i += 1
	end

	['index', 'about', 'colateral'].each do |item|
		File.open(File.join($base, "#{item}.html"), 'w') do |file|
		      h1 = item
		      item = item
		      cap = nil
       		file.write(template.result(binding))
    	end
	end
	
	unless abort
		print "\n\tdone\n"
	end
end


