---
lang: es
font: Baskerville
mono: Courier
chap: "Capítulo "
sect: "Sección "
fig: "Figura "
tab: "Tabla "
index:
    - cap0
    - cap1
    - cap2
    - cap3
    - cap4
    - cap5
    - cap6
    
headers:
    - Notas antes de partir
    - Personal Information Glut
    - Folders & Tagging redundancy
    - RSSocial fatigue
    - Kill Inbox
    - The wiki old days
    - Look Ma! Without tabs

order: 
  - cap0:
      title: Notas antes de partir
  - cap1:
      title: Personal Information Glut
  - cap2:
      title: Folders & Tagging redundancy
  - cap3:
      title: RSSocial fatigue
  - cap4:
      title: Kill Inbox
  - cap5:
      title: The wiki old days
  - cap6:
      title: Look Ma! Without tabs
  - cap7:
      title: The sexy job


#order:
#	- cap0:
#		- title: Notas antes de partir
#	- cap1:
#	- cap2:
#	- cap3:
#	- cap4:
#	- cap5:
#	- cap6:
#	- cap7:
#    - anx1
#    - anx2
#    - anx3
